name: "HAVNC"
description: "VNC straight to your dashboard"
version: "0.0.9"
slug: "havnc"
init: false
full_access: false
arch:
  - aarch64
  - amd64
ports:
  8080/tcp: 8080
options:
  url: "http://homeassistant:8123"
  resolution: "768x1024"
  password: null
schema:
  url: "str"
  resolution: "str"
  password: "password"
